services:
  - type: web
    name: laravel-app
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    startCommand: php artisan migrate --force && apache2-foreground
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://laravel-app.onrender.com
      # MySQL Database Configuration
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql10.freesqldatabase.com
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: sql10793636
      - key: DB_USERNAME
        value: sql10793636
      - key: DB_PASSWORD
        value: GWVpxlf7Dp
